server:
  port: 8081
  use-forward-headers: true
  compression:
    enabled: false
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
spring:
  resources:
    static-locations: classpath:/tessdata/
  profiles:
    active: 'dev'
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver #com.p6spy.engine.spy.P6SpyDriver #p6spy:
    url: jdbc:mysql://127.0.0.1:3306/myxy?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123



mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.xw.entity
logging:
  level:
    run.halo.app: debug
    org.jnativehook: error
  path: ${user.home}/.myidea/logs